---
- name: create user
  hosts: all
  vars_files:
    - user_file.yml
    - vault.yml
  tasks:
    - name: group
      group:
        name: "{{ item.job }}" 
        state: present
      loop: "{{ users }}"
    - name: user
      user:
        name: "{{ item.name }}" 
        groups: developer
        append: yes
        password: "{{ dev_pass | password_hash('sha512') }}"
        state: present
      loop: "{{ users }}"
      when:
        - item.job == 'developer'
        - inventory_hostname in groups['web']

