---
- hosts: web
  become: yes
  tasks:
    - name: web 
      yum:
        name: httpd
        state: present
      notify: apache restart

  handlers:
    - name: apache restart
      service:
        name: httpd
        state: restarted
